let data = {
    examName: "SSC Ka Khatarnaak Exam",
    examTime: "90 min",
    positiveMark: 2,
    negativeMark: 0.5,
    examData: [
        {
            section: "General Knowledge",
            sectionSelected: "",
            sectionSelectedClass: "",
            timeSpent: "",
            questions: [
                {
                    numb: 1,
                    question: "What does HTML stand for?",
                    answer: "Hyper Text Markup Language",
                    options: [
                        "Hyper Text Preprocessor",
                        "Hyper Text Markup Language",
                        "Hyper Text Multiple Language",
                        "Hyper Tool Multi Language",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 2,
                    question: "What does CSS stand for?",
                    answer: "Cascading Style Sheet",
                    options: [
                        "Common Style Sheet",
                        "Colorful Style Sheet",
                        "Computer Style Sheet",
                        "Cascading Style Sheet",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 3,
                    question: "What does PHP stand for?",
                    answer: "Hypertext Preprocessor",
                    options: [
                        "Hypertext Preprocessor",
                        "Hypertext Programming",
                        "Hypertext Preprogramming",
                        "Hometext Preprocessor",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 4,
                    question: "What does SQL stand for?",
                    answer: "Structured Query Language",
                    options: [
                        "Stylish Question Language",
                        "Stylesheet Query Language",
                        "Statement Question Language",
                        "Structured Query Language",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 5,
                    question: "What does XML stand for?",
                    answer: "eXtensible Markup Language",
                    options: [
                        "eXtensible Markup Language",
                        "eXecutable Multiple Language",
                        "eXTra Multi-Program Language",
                        "eXamine Multiple Language",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
            ],
        },
        {
            section: "Knowledge Ka General",
            sectionSelected: "",
            sectionSelectedClass: "",
            timeSpent: "",
            questions: [
                {
                    numb: 1,
                    question: "HTML Ka Stand?",
                    answer: "Hyper Text Markup Language",
                    options: [
                        "Hyper Text Preprocessor",
                        "Hyper Text Markup Language",
                        "Hyper Text Multiple Language",
                        "Hyper Tool Multi Language",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 2,
                    question: "CSS stand for?",
                    answer: "Cascading Style Sheet",
                    options: [
                        "Common Style Sheet",
                        "Colorful Style Sheet",
                        "Computer Style Sheet",
                        "Cascading Style Sheet",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 3,
                    question: "What does PHP stand for?",
                    answer: "Hypertext Preprocessor",
                    options: [
                        "Hypertext Preprocessor",
                        "Hypertext Programming",
                        "Hypertext Preprogramming",
                        "Hometext Preprocessor",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
                {
                    numb: 4,
                    question: "What does SQL stand for?",
                    answer: "Structured Query Language",
                    options: [
                        "Stylish Question Language",
                        "Stylesheet Query Language",
                        "Statement Question Language",
                        "Structured Query Language",
                    ],
                    optionSelected: "",
                    optionSelectedClass: "",
                    timeSpent: "",
                },
            ],
        },
    ],
}
